plugins {
    id("java-library")
    id("maven-publish")
    id("net.minecraftforge.gradle") version "[6.0,6.2)"
    id("idea")
    id("me.modmuss50.mod-publish-plugin") version "1.1.0"
}

stonecutter {
    def agricraft = property("agricraft_version") != null
    constants["agricraft"] = agricraft
    def mysticalagriculture = property("mysticalagriculture_version") != null
    constants["mysticalagriculture"] = mysticalagriculture
}

version = "${property("mod_version")}-${property("mod_loader")}-${stonecutter.current.version}"
group = mod_group_id
base {
    archivesName = mod_id
}

java {
    withSourcesJar()
    targetCompatibility = property("java_version")
    sourceCompatibility = property("java_version")
}

repositories {

}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    runs {
        client {
        }

        server {
            args '--nogui'
        }

        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "${project.mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

publishMods {
    file = jar.archiveFile.get()
    displayName = "${property("mod_name")} ${property("mod_version")} for ${stonecutter.current.version}"
    version = property("mod_version") as String
    changelog = rootProject.file("CHANGELOG.md").getText()
    type = STABLE
    modLoaders.add("neoforge")

    dryRun = providers.environmentVariable("MODRINTH_TOKEN").getOrNull() == null
            || providers.environmentVariable("CURSEFORGE_TOKEN").getOrNull() == null

    modrinth {
        projectId = property("publish.modrinth") as String
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(stonecutter.current.version)
    }

    curseforge {
        projectId = property("publish.curseforge") as String
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add(stonecutter.current.version)
    }
}

publishing {
    repositories {
        maven {
            name = "RemplersRepo"
            url = "https://maven.rempler.com/releases/"
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }

    publications {
        register('mavenJava', MavenPublication) {
            groupId "${property("mod_group_id")}.${property("mod_loader")}"
            artifactId "${property("mod_id")}-${property("mod_loader")}-${property("mod_version")}"
            version stonecutter.current.version
            from components.java
        }
    }
}
