# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=2.0.0
mod.group=com.rempler.jagahm
mod.id=jagahm
mod.name=Just another growth and harvest mod

# Global dependencies
deps.fabric_loader=0.17.2
mod_loader=fabric