# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod.version=5.0.1
mod.group=com.rempler.jagahm
mod.id=jagahm
mod.name=Just another growth and harvest mod

# Publish IDs
publish.modrinth=bpEHi5AO
publish.curseforge=674698

# Global dependencies
deps.fabric_loader=0.18.5
mod_loader=fabric