# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod_version=5.1.0
mod_group_id=com.rempler.jagahm
mod_id=jagahm
mod_name=Just another growth and harvest mod
mod_license=All Rights Reserved
mod_authors=Rempler
mod_description=A simple mod that adds growth and harvest mechanics to Minecraft.

# Publish IDs
publish.modrinth=bpEHi5AO
publish.curseforge=674698

# Global dependencies
mod_loader=forge
