minecraft_version=1.16.5
minecraft_version_range=[1.16.5]
forge_version=36.2.42
forge_version_range=[36,)
loader_version_range=[36,)
mapping_channel=official
mapping_version=1.16.5

java_version=8

# Dependencies Versions
agricraft_version=3809887
infinitylib_version=3539825
cucumber_version=4.1.12
mysticalagriculture_version=4.2.6
